"""Create products table

Revision ID: 541fbfb4452a
Revises: 0c066d39492e
Create Date: 2026-09-28 11:16:18.808712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541fbfb4452a'
down_revision = '0c066d39492e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discounted_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=150), nullable=True),
    sa.Column('size', sa.JSON(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
