"""rename profile to profile_image

Revision ID: 8910ff4b6f19
Revises: 462ad3d81c04
Create Date: 2026-08-26 12:46:27.276527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8910ff4b6f19'
down_revision = '462ad3d81c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=128), nullable=True))
        batch_op.drop_column('profile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
