"""create user table

Revision ID: a24f5346864c
Revises: c4b8b1d5ab68
Create Date: 2026-08-22 19:43:59.037254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24f5346864c'
down_revision = 'c4b8b1d5ab68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=False),
    sa.Column('subtotal', sa.FLOAT(), nullable=False),
    sa.Column('shipping', sa.FLOAT(), nullable=False),
    sa.Column('total', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###
